# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kUC8daJuy-nzsFA9CmsSjYdDWaQfUBC0
"""

# !pip install googletrans

from googletrans import Translator

trans = Translator()

text = trans.translate("मेरा नाम राम है और मैं एक अच्छा लड़का हूँ").text

text

# pip install gtts

from gtts import gTTS

import os

#pip install pyttsx3

import pyttsx3

# pip install espeak

# engine = pyttsx3.init(espeak)

# ! pip install pypiwin32





from gtts import gTTS

tts = gTTS(text)

tts.save("text.mp3")

